//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Pokemon.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PokemonDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PokemonDBEntities object using the connection string found in the 'PokemonDBEntities' section of the application configuration file.
        /// </summary>
        public PokemonDBEntities() : base("name=PokemonDBEntities", "PokemonDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PokemonDBEntities object.
        /// </summary>
        public PokemonDBEntities(string connectionString) : base(connectionString, "PokemonDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PokemonDBEntities object.
        /// </summary>
        public PokemonDBEntities(EntityConnection connection) : base(connection, "PokemonDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PokemonBase> PokemonBases
        {
            get
            {
                if ((_PokemonBases == null))
                {
                    _PokemonBases = base.CreateObjectSet<PokemonBase>("PokemonBases");
                }
                return _PokemonBases;
            }
        }
        private ObjectSet<PokemonBase> _PokemonBases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeneratedPokemon> GeneratedPokemons
        {
            get
            {
                if ((_GeneratedPokemons == null))
                {
                    _GeneratedPokemons = base.CreateObjectSet<GeneratedPokemon>("GeneratedPokemons");
                }
                return _GeneratedPokemons;
            }
        }
        private ObjectSet<GeneratedPokemon> _GeneratedPokemons;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PokemonBases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPokemonBases(PokemonBase pokemonBase)
        {
            base.AddObject("PokemonBases", pokemonBase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeneratedPokemons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeneratedPokemons(GeneratedPokemon generatedPokemon)
        {
            base.AddObject("GeneratedPokemons", generatedPokemon);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PokemonDBModel", Name="GeneratedPokemon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeneratedPokemon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeneratedPokemon object.
        /// </summary>
        /// <param name="generatedPokemonId">Initial value of the GeneratedPokemonId property.</param>
        /// <param name="lvl">Initial value of the Lvl property.</param>
        /// <param name="genAttackStat">Initial value of the GenAttackStat property.</param>
        /// <param name="genDefenseStat">Initial value of the GenDefenseStat property.</param>
        /// <param name="genSpAttackStat">Initial value of the GenSpAttackStat property.</param>
        /// <param name="genSpDefenseStat">Initial value of the GenSpDefenseStat property.</param>
        /// <param name="genSpeedStat">Initial value of the GenSpeedStat property.</param>
        /// <param name="natureOne">Initial value of the NatureOne property.</param>
        /// <param name="natureTwo">Initial value of the NatureTwo property.</param>
        /// <param name="shined">Initial value of the Shined property.</param>
        /// <param name="ability">Initial value of the Ability property.</param>
        /// <param name="currentExp">Initial value of the CurrentExp property.</param>
        public static GeneratedPokemon CreateGeneratedPokemon(global::System.Int32 generatedPokemonId, global::System.Int32 lvl, global::System.Int32 genAttackStat, global::System.Int32 genDefenseStat, global::System.Int32 genSpAttackStat, global::System.Int32 genSpDefenseStat, global::System.Int32 genSpeedStat, global::System.String natureOne, global::System.String natureTwo, global::System.Boolean shined, global::System.String ability, global::System.Int32 currentExp)
        {
            GeneratedPokemon generatedPokemon = new GeneratedPokemon();
            generatedPokemon.GeneratedPokemonId = generatedPokemonId;
            generatedPokemon.Lvl = lvl;
            generatedPokemon.GenAttackStat = genAttackStat;
            generatedPokemon.GenDefenseStat = genDefenseStat;
            generatedPokemon.GenSpAttackStat = genSpAttackStat;
            generatedPokemon.GenSpDefenseStat = genSpDefenseStat;
            generatedPokemon.GenSpeedStat = genSpeedStat;
            generatedPokemon.NatureOne = natureOne;
            generatedPokemon.NatureTwo = natureTwo;
            generatedPokemon.Shined = shined;
            generatedPokemon.Ability = ability;
            generatedPokemon.CurrentExp = currentExp;
            return generatedPokemon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GeneratedPokemonId
        {
            get
            {
                return _GeneratedPokemonId;
            }
            set
            {
                if (_GeneratedPokemonId != value)
                {
                    OnGeneratedPokemonIdChanging(value);
                    ReportPropertyChanging("GeneratedPokemonId");
                    _GeneratedPokemonId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GeneratedPokemonId");
                    OnGeneratedPokemonIdChanged();
                }
            }
        }
        private global::System.Int32 _GeneratedPokemonId;
        partial void OnGeneratedPokemonIdChanging(global::System.Int32 value);
        partial void OnGeneratedPokemonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Lvl
        {
            get
            {
                return _Lvl;
            }
            set
            {
                OnLvlChanging(value);
                ReportPropertyChanging("Lvl");
                _Lvl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lvl");
                OnLvlChanged();
            }
        }
        private global::System.Int32 _Lvl;
        partial void OnLvlChanging(global::System.Int32 value);
        partial void OnLvlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenAttackStat
        {
            get
            {
                return _GenAttackStat;
            }
            set
            {
                OnGenAttackStatChanging(value);
                ReportPropertyChanging("GenAttackStat");
                _GenAttackStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenAttackStat");
                OnGenAttackStatChanged();
            }
        }
        private global::System.Int32 _GenAttackStat;
        partial void OnGenAttackStatChanging(global::System.Int32 value);
        partial void OnGenAttackStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenDefenseStat
        {
            get
            {
                return _GenDefenseStat;
            }
            set
            {
                OnGenDefenseStatChanging(value);
                ReportPropertyChanging("GenDefenseStat");
                _GenDefenseStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenDefenseStat");
                OnGenDefenseStatChanged();
            }
        }
        private global::System.Int32 _GenDefenseStat;
        partial void OnGenDefenseStatChanging(global::System.Int32 value);
        partial void OnGenDefenseStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenSpAttackStat
        {
            get
            {
                return _GenSpAttackStat;
            }
            set
            {
                OnGenSpAttackStatChanging(value);
                ReportPropertyChanging("GenSpAttackStat");
                _GenSpAttackStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenSpAttackStat");
                OnGenSpAttackStatChanged();
            }
        }
        private global::System.Int32 _GenSpAttackStat;
        partial void OnGenSpAttackStatChanging(global::System.Int32 value);
        partial void OnGenSpAttackStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenSpDefenseStat
        {
            get
            {
                return _GenSpDefenseStat;
            }
            set
            {
                OnGenSpDefenseStatChanging(value);
                ReportPropertyChanging("GenSpDefenseStat");
                _GenSpDefenseStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenSpDefenseStat");
                OnGenSpDefenseStatChanged();
            }
        }
        private global::System.Int32 _GenSpDefenseStat;
        partial void OnGenSpDefenseStatChanging(global::System.Int32 value);
        partial void OnGenSpDefenseStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenSpeedStat
        {
            get
            {
                return _GenSpeedStat;
            }
            set
            {
                OnGenSpeedStatChanging(value);
                ReportPropertyChanging("GenSpeedStat");
                _GenSpeedStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenSpeedStat");
                OnGenSpeedStatChanged();
            }
        }
        private global::System.Int32 _GenSpeedStat;
        partial void OnGenSpeedStatChanging(global::System.Int32 value);
        partial void OnGenSpeedStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NatureOne
        {
            get
            {
                return _NatureOne;
            }
            set
            {
                OnNatureOneChanging(value);
                ReportPropertyChanging("NatureOne");
                _NatureOne = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NatureOne");
                OnNatureOneChanged();
            }
        }
        private global::System.String _NatureOne;
        partial void OnNatureOneChanging(global::System.String value);
        partial void OnNatureOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NatureTwo
        {
            get
            {
                return _NatureTwo;
            }
            set
            {
                OnNatureTwoChanging(value);
                ReportPropertyChanging("NatureTwo");
                _NatureTwo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NatureTwo");
                OnNatureTwoChanged();
            }
        }
        private global::System.String _NatureTwo;
        partial void OnNatureTwoChanging(global::System.String value);
        partial void OnNatureTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FirstEvolved
        {
            get
            {
                return _FirstEvolved;
            }
            set
            {
                OnFirstEvolvedChanging(value);
                ReportPropertyChanging("FirstEvolved");
                _FirstEvolved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstEvolved");
                OnFirstEvolvedChanged();
            }
        }
        private Nullable<global::System.Int32> _FirstEvolved;
        partial void OnFirstEvolvedChanging(Nullable<global::System.Int32> value);
        partial void OnFirstEvolvedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SecondEvolved
        {
            get
            {
                return _SecondEvolved;
            }
            set
            {
                OnSecondEvolvedChanging(value);
                ReportPropertyChanging("SecondEvolved");
                _SecondEvolved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SecondEvolved");
                OnSecondEvolvedChanged();
            }
        }
        private Nullable<global::System.Int32> _SecondEvolved;
        partial void OnSecondEvolvedChanging(Nullable<global::System.Int32> value);
        partial void OnSecondEvolvedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Shined
        {
            get
            {
                return _Shined;
            }
            set
            {
                OnShinedChanging(value);
                ReportPropertyChanging("Shined");
                _Shined = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shined");
                OnShinedChanged();
            }
        }
        private global::System.Boolean _Shined;
        partial void OnShinedChanging(global::System.Boolean value);
        partial void OnShinedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ability
        {
            get
            {
                return _Ability;
            }
            set
            {
                OnAbilityChanging(value);
                ReportPropertyChanging("Ability");
                _Ability = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ability");
                OnAbilityChanged();
            }
        }
        private global::System.String _Ability;
        partial void OnAbilityChanging(global::System.String value);
        partial void OnAbilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CurrentExp
        {
            get
            {
                return _CurrentExp;
            }
            set
            {
                OnCurrentExpChanging(value);
                ReportPropertyChanging("CurrentExp");
                _CurrentExp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentExp");
                OnCurrentExpChanged();
            }
        }
        private global::System.Int32 _CurrentExp;
        partial void OnCurrentExpChanging(global::System.Int32 value);
        partial void OnCurrentExpChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PokemonDBModel", Name="PokemonBase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PokemonBase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PokemonBase object.
        /// </summary>
        /// <param name="pokemonId">Initial value of the PokemonId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="evoLevel">Initial value of the EvoLevel property.</param>
        /// <param name="abilityOne">Initial value of the AbilityOne property.</param>
        /// <param name="abilityTwo">Initial value of the AbilityTwo property.</param>
        /// <param name="abilityThree">Initial value of the AbilityThree property.</param>
        /// <param name="maleGenderPercent">Initial value of the MaleGenderPercent property.</param>
        /// <param name="primaryType">Initial value of the PrimaryType property.</param>
        /// <param name="subType">Initial value of the SubType property.</param>
        /// <param name="hPStat">Initial value of the HPStat property.</param>
        /// <param name="attackStat">Initial value of the AttackStat property.</param>
        /// <param name="defenseStat">Initial value of the DefenseStat property.</param>
        /// <param name="spAttackStat">Initial value of the SpAttackStat property.</param>
        /// <param name="spDefenseStat">Initial value of the SpDefenseStat property.</param>
        /// <param name="speedStat">Initial value of the SpeedStat property.</param>
        /// <param name="levelSpeed">Initial value of the LevelSpeed property.</param>
        /// <param name="baseExp">Initial value of the BaseExp property.</param>
        /// <param name="baseCatch">Initial value of the BaseCatch property.</param>
        public static PokemonBase CreatePokemonBase(global::System.Int32 pokemonId, global::System.String name, global::System.Int32 evoLevel, global::System.String abilityOne, global::System.String abilityTwo, global::System.String abilityThree, global::System.Single maleGenderPercent, global::System.String primaryType, global::System.String subType, global::System.Int32 hPStat, global::System.Int32 attackStat, global::System.Int32 defenseStat, global::System.Int32 spAttackStat, global::System.Int32 spDefenseStat, global::System.Int32 speedStat, global::System.Int32 levelSpeed, global::System.Int32 baseExp, global::System.Int32 baseCatch)
        {
            PokemonBase pokemonBase = new PokemonBase();
            pokemonBase.PokemonId = pokemonId;
            pokemonBase.Name = name;
            pokemonBase.EvoLevel = evoLevel;
            pokemonBase.AbilityOne = abilityOne;
            pokemonBase.AbilityTwo = abilityTwo;
            pokemonBase.AbilityThree = abilityThree;
            pokemonBase.MaleGenderPercent = maleGenderPercent;
            pokemonBase.PrimaryType = primaryType;
            pokemonBase.SubType = subType;
            pokemonBase.HPStat = hPStat;
            pokemonBase.AttackStat = attackStat;
            pokemonBase.DefenseStat = defenseStat;
            pokemonBase.SpAttackStat = spAttackStat;
            pokemonBase.SpDefenseStat = spDefenseStat;
            pokemonBase.SpeedStat = speedStat;
            pokemonBase.LevelSpeed = levelSpeed;
            pokemonBase.BaseExp = baseExp;
            pokemonBase.BaseCatch = baseCatch;
            return pokemonBase;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PokemonId
        {
            get
            {
                return _PokemonId;
            }
            set
            {
                if (_PokemonId != value)
                {
                    OnPokemonIdChanging(value);
                    ReportPropertyChanging("PokemonId");
                    _PokemonId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PokemonId");
                    OnPokemonIdChanged();
                }
            }
        }
        private global::System.Int32 _PokemonId;
        partial void OnPokemonIdChanging(global::System.Int32 value);
        partial void OnPokemonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EvoLevel
        {
            get
            {
                return _EvoLevel;
            }
            set
            {
                OnEvoLevelChanging(value);
                ReportPropertyChanging("EvoLevel");
                _EvoLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EvoLevel");
                OnEvoLevelChanged();
            }
        }
        private global::System.Int32 _EvoLevel;
        partial void OnEvoLevelChanging(global::System.Int32 value);
        partial void OnEvoLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AbilityOne
        {
            get
            {
                return _AbilityOne;
            }
            set
            {
                OnAbilityOneChanging(value);
                ReportPropertyChanging("AbilityOne");
                _AbilityOne = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AbilityOne");
                OnAbilityOneChanged();
            }
        }
        private global::System.String _AbilityOne;
        partial void OnAbilityOneChanging(global::System.String value);
        partial void OnAbilityOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AbilityTwo
        {
            get
            {
                return _AbilityTwo;
            }
            set
            {
                OnAbilityTwoChanging(value);
                ReportPropertyChanging("AbilityTwo");
                _AbilityTwo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AbilityTwo");
                OnAbilityTwoChanged();
            }
        }
        private global::System.String _AbilityTwo;
        partial void OnAbilityTwoChanging(global::System.String value);
        partial void OnAbilityTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AbilityThree
        {
            get
            {
                return _AbilityThree;
            }
            set
            {
                OnAbilityThreeChanging(value);
                ReportPropertyChanging("AbilityThree");
                _AbilityThree = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AbilityThree");
                OnAbilityThreeChanged();
            }
        }
        private global::System.String _AbilityThree;
        partial void OnAbilityThreeChanging(global::System.String value);
        partial void OnAbilityThreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaleGenderPercent
        {
            get
            {
                return _MaleGenderPercent;
            }
            set
            {
                OnMaleGenderPercentChanging(value);
                ReportPropertyChanging("MaleGenderPercent");
                _MaleGenderPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaleGenderPercent");
                OnMaleGenderPercentChanged();
            }
        }
        private global::System.Single _MaleGenderPercent;
        partial void OnMaleGenderPercentChanging(global::System.Single value);
        partial void OnMaleGenderPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryType
        {
            get
            {
                return _PrimaryType;
            }
            set
            {
                OnPrimaryTypeChanging(value);
                ReportPropertyChanging("PrimaryType");
                _PrimaryType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryType");
                OnPrimaryTypeChanged();
            }
        }
        private global::System.String _PrimaryType;
        partial void OnPrimaryTypeChanging(global::System.String value);
        partial void OnPrimaryTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubType
        {
            get
            {
                return _SubType;
            }
            set
            {
                OnSubTypeChanging(value);
                ReportPropertyChanging("SubType");
                _SubType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubType");
                OnSubTypeChanged();
            }
        }
        private global::System.String _SubType;
        partial void OnSubTypeChanging(global::System.String value);
        partial void OnSubTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HPStat
        {
            get
            {
                return _HPStat;
            }
            set
            {
                OnHPStatChanging(value);
                ReportPropertyChanging("HPStat");
                _HPStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HPStat");
                OnHPStatChanged();
            }
        }
        private global::System.Int32 _HPStat;
        partial void OnHPStatChanging(global::System.Int32 value);
        partial void OnHPStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttackStat
        {
            get
            {
                return _AttackStat;
            }
            set
            {
                OnAttackStatChanging(value);
                ReportPropertyChanging("AttackStat");
                _AttackStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttackStat");
                OnAttackStatChanged();
            }
        }
        private global::System.Int32 _AttackStat;
        partial void OnAttackStatChanging(global::System.Int32 value);
        partial void OnAttackStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DefenseStat
        {
            get
            {
                return _DefenseStat;
            }
            set
            {
                OnDefenseStatChanging(value);
                ReportPropertyChanging("DefenseStat");
                _DefenseStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefenseStat");
                OnDefenseStatChanged();
            }
        }
        private global::System.Int32 _DefenseStat;
        partial void OnDefenseStatChanging(global::System.Int32 value);
        partial void OnDefenseStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SpAttackStat
        {
            get
            {
                return _SpAttackStat;
            }
            set
            {
                OnSpAttackStatChanging(value);
                ReportPropertyChanging("SpAttackStat");
                _SpAttackStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpAttackStat");
                OnSpAttackStatChanged();
            }
        }
        private global::System.Int32 _SpAttackStat;
        partial void OnSpAttackStatChanging(global::System.Int32 value);
        partial void OnSpAttackStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SpDefenseStat
        {
            get
            {
                return _SpDefenseStat;
            }
            set
            {
                OnSpDefenseStatChanging(value);
                ReportPropertyChanging("SpDefenseStat");
                _SpDefenseStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpDefenseStat");
                OnSpDefenseStatChanged();
            }
        }
        private global::System.Int32 _SpDefenseStat;
        partial void OnSpDefenseStatChanging(global::System.Int32 value);
        partial void OnSpDefenseStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SpeedStat
        {
            get
            {
                return _SpeedStat;
            }
            set
            {
                OnSpeedStatChanging(value);
                ReportPropertyChanging("SpeedStat");
                _SpeedStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpeedStat");
                OnSpeedStatChanged();
            }
        }
        private global::System.Int32 _SpeedStat;
        partial void OnSpeedStatChanging(global::System.Int32 value);
        partial void OnSpeedStatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LevelSpeed
        {
            get
            {
                return _LevelSpeed;
            }
            set
            {
                OnLevelSpeedChanging(value);
                ReportPropertyChanging("LevelSpeed");
                _LevelSpeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LevelSpeed");
                OnLevelSpeedChanged();
            }
        }
        private global::System.Int32 _LevelSpeed;
        partial void OnLevelSpeedChanging(global::System.Int32 value);
        partial void OnLevelSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BaseExp
        {
            get
            {
                return _BaseExp;
            }
            set
            {
                OnBaseExpChanging(value);
                ReportPropertyChanging("BaseExp");
                _BaseExp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseExp");
                OnBaseExpChanged();
            }
        }
        private global::System.Int32 _BaseExp;
        partial void OnBaseExpChanging(global::System.Int32 value);
        partial void OnBaseExpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BaseCatch
        {
            get
            {
                return _BaseCatch;
            }
            set
            {
                OnBaseCatchChanging(value);
                ReportPropertyChanging("BaseCatch");
                _BaseCatch = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseCatch");
                OnBaseCatchChanged();
            }
        }
        private global::System.Int32 _BaseCatch;
        partial void OnBaseCatchChanging(global::System.Int32 value);
        partial void OnBaseCatchChanged();

        #endregion
    
    }

    #endregion
    
}
